### ISSUE TITLE
Installation fails on Ubuntu 14.04 with R version 3.3.0

### ISSUE THREAD

**Issue by anthony-aylward** [hms-dbmi/spp#2]
Installation fails on Ubuntu 14.04 with R version 3.3.0

Here are the errors I get when trying to install:

[spp-error.txt](https://github.com/hms-dbmi/spp/files/258942/spp-error.txt)

**Comment by colenr** [comment]
I get the exact same error generating bed2vector.o on Centos 6 with R 3.3.0.  I attempted installing in an older version of R and this worked without issue.  

Is there a fix to get spp 1.13 installed in R 3.3.0?

**Comment by lkhamvongsa** [comment]
I have the same installation problem with spp 1.13 in R 3.3.0 on Ubuntu 14.04. 

I tried to install version 1.11 of spp in R 3.3.0 and I also have a compilation error.

**Comment by pkharchenko** [comment]
It seems that Rmath.h has changed in R 3.3.0 so it's no longer compatible with "extern C" clauses. I've released a 1.14 fix:
https://github.com/hms-dbmi/spp/releases/tag/1.14

Please try it out and let me know if you have further problems.

**Comment by devmotion** [comment]
Installation still fails on Archlinux with R 3.3.0. I get the following compilation error:

``` R
> devtools::install_github('hms-dbmi/spp', build_vignettes = FALSE)
Downloading GitHub repo hms-dbmi/spp@master
from URL https://api.github.com/repos/hms-dbmi/spp/zipball/master
Installing spp
Skipping 1 unavailable package: Rsamtools
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpXY2Psb/devtools52a325b69eb/hms-dbmi-spp-2c93f5e' --library='/home/david/R/x86_64-pc-linux-gnu-library/3.3'  \
  --install-tests 

* installing *source* package ‘spp’ ...
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for BZ2_bzDecompressInit in -lbz2... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking how to run the C++ preprocessor... g++ -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for Boost headers version >= 1.41.0... yes
checking for Boost's header version... 1_60
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -I/usr/include/R/ -DNDEBUG  -D_FORTIFY_SOURCE=2   -I./ -D_FASTMAP -DMAQ_LONGREADS      -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c bed2vector.cpp -o bed2vector.o
In file included from /usr/include/c++/6.1.1/ext/hash_map:60:0,
                 from pc.h:4,
                 from bed2vector.cpp:1:
/usr/include/c++/6.1.1/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^~~~~~~
bed2vector.cpp: In function ‘SEXPREC* read_bed_ends(SEXP)’:
bed2vector.cpp:118:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:163:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:163:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:165:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:165:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:169:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_meland_old(SEXP)’:
bed2vector.cpp:254:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:296:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:296:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:298:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:298:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:302:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_meland(SEXP, SEXP)’:
bed2vector.cpp:432:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:476:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:476:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:478:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:478:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:482:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_eland_mismatches(SEXP)’:
bed2vector.cpp:624:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:692:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:692:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:694:10: error: ‘li��� was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:694:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:698:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_eland(SEXP, SEXP, SEXP)’:
bed2vector.cpp:817:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:868:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:868:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:870:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:870:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:874:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_eland_extended(SEXP, SEXP, SEXP)’:
bed2vector.cpp:1004:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:1078:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:1078:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:1080:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:1080:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:1084:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_eland_multi(SEXP, SEXP, SEXP)’:
bed2vector.cpp:1213:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:1366:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:1366:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:1368:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:1368:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:1372:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_bowtie(SEXP, SEXP)’:
bed2vector.cpp:1500:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:1575:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:1575:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:1577:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:1577:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:1581:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_helicostabf(SEXP, SEXP)’:
bed2vector.cpp:1714:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:1792:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:1792:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:1794:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:1794:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:1798:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_maqmap(SEXP, SEXP)’:
bed2vector.cpp:1941:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:1984:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:1984:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:1986:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:1986:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:1990:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_tagalign(SEXP)’:
bed2vector.cpp:2119:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:2161:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:2161:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:2163:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:2163:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:2167:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_arachne(SEXP)’:
bed2vector.cpp:2270:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:2329:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:2329:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:2331:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:2331:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:2335:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
bed2vector.cpp: In function ‘SEXPREC* read_arachne_long(SEXP)’:
bed2vector.cpp:2441:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:2530:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:2530:77: error: qualified-id in declaration before ‘li’
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:2532:10: error: ‘li’ was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:2532:23: error: request for member ‘end’ in ‘cind_map’, which is of non-class type ‘int’
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:2536:10: error: no match for ‘operator[]’ (operand types are ‘int’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cind_map[chr]=cind;
          ^
/usr/lib64/R/etc/Makeconf:141: recipe for target 'bed2vector.o' failed
make: *** [bed2vector.o] Error 1
ERROR: compilation failed for package ‘spp’
* removing ‘/home/david/R/x86_64-pc-linux-gnu-library/3.3/spp’
Error: Command failed (1)
```

**Comment by anthony-aylward** [comment]
The 1.14 fix installs and loads successfully on my Ubuntu 14.04 system under R 3.3.0.

**Comment by colenr** [comment]
The 1.14 fix installs and loads on my Centos 6 under R 3.3.0 as well.  Thank you for the fix.

**Comment by jeizenga** [comment]
I am still seeing the same C++ compilation errors in version 1.14 on both Debian 9.9 and Ubuntu 18.04 using R 3.4.4. What is the fix for this?

**Comment by hcph** [comment]
using the fixed package still seeing the same error on Ubuntu 14.04 with R 3.6
